package repository;

/**
 * SQL-диалект для различий между СУБД.
 */
public enum SqlDialect {
    SQLITE,
    POSTGRESQL,
    MYSQL,
    FIREBIRD;

    public static SqlDialect from(DatabaseConfig.Type type) {
        return switch (type) {
            case SQLITE -> SQLITE;
            case POSTGRESQL -> POSTGRESQL;
            case MYSQL -> MYSQL;
            case FIREBIRD -> FIREBIRD;
            case CUSTOM -> throw new IllegalArgumentException("Custom JDBC requires explicit SQL adaptation");
        };
    }

    public boolean supportsInformationSchema() {
        return this == POSTGRESQL || this == MYSQL;
    }

    public boolean supportsIfNotExistsOnAddColumn() {
        return this == POSTGRESQL || this == MYSQL;
    }

    public String identityColumn() {
        return switch (this) {
            case SQLITE -> "INTEGER PRIMARY KEY AUTOINCREMENT";
            case POSTGRESQL -> "BIGSERIAL PRIMARY KEY";
            case MYSQL -> "BIGINT AUTO_INCREMENT PRIMARY KEY";
            case FIREBIRD -> "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
        };
    }

    public String textType() {
        return switch (this) {
            case MYSQL -> "LONGTEXT";
            case FIREBIRD -> "BLOB SUB_TYPE TEXT";
            default -> "TEXT";
        };
    }

    public String timestampType() {
        return switch (this) {
            case SQLITE -> "TEXT";
            case POSTGRESQL, MYSQL -> "VARCHAR(32)";
            case FIREBIRD -> "VARCHAR(32)";
        };
    }

    public String generatedTimestampType() {
        return switch (this) {
            case SQLITE -> "TEXT";
            case POSTGRESQL, FIREBIRD -> "TIMESTAMP";
            case MYSQL -> "DATETIME";
        };
    }

    public String settingsKeyIdentifier() {
        return this == MYSQL ? "`key`" : "key";
    }

    public String insertIgnore(String table, String columnsPlaceholders) {
        return switch (this) {
            case SQLITE -> "INSERT OR IGNORE INTO " + table + columnsPlaceholders;
            case POSTGRESQL -> "INSERT INTO " + table + columnsPlaceholders + " ON CONFLICT DO NOTHING";
            case MYSQL -> "INSERT IGNORE INTO " + table + columnsPlaceholders;
            case FIREBIRD -> "UPDATE OR INSERT INTO " + table + columnsPlaceholders.replace(" VALUES", " VALUES") + " MATCHING(" + inferMatchingColumns(table) + ")";
        };
    }

    public String insertIgnoreOnConstraint(String table, String columnsPlaceholders, String conflictTarget) {
        return switch (this) {
            case SQLITE -> "INSERT OR IGNORE INTO " + table + columnsPlaceholders;
            case POSTGRESQL -> "INSERT INTO " + table + columnsPlaceholders + " ON CONFLICT(" + conflictTarget + ") DO NOTHING";
            case MYSQL -> "INSERT IGNORE INTO " + table + columnsPlaceholders;
            case FIREBIRD -> "UPDATE OR INSERT INTO " + table + columnsPlaceholders + " MATCHING(" + conflictTarget + ")";
        };
    }

    public String upsertTaskSql() {
        return switch (this) {
            case SQLITE, POSTGRESQL -> """
                INSERT INTO tasks(
                    id, title, description, start_time, end_time, priority,
                    category, completed, overdue, created_at, updated_at,
                    sort_index, owner_user_id, recurrence_rule, reminder_offset, recurrence_end
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(id) DO UPDATE SET
                    title=excluded.title,
                    description=excluded.description,
                    start_time=excluded.start_time,
                    end_time=excluded.end_time,
                    priority=excluded.priority,
                    category=excluded.category,
                    completed=excluded.completed,
                    overdue=excluded.overdue,
                    updated_at=excluded.updated_at,
                    sort_index=excluded.sort_index,
                    owner_user_id=excluded.owner_user_id,
                    recurrence_rule=excluded.recurrence_rule,
                    reminder_offset=excluded.reminder_offset,
                    recurrence_end=excluded.recurrence_end
                """;
            case MYSQL -> """
                INSERT INTO tasks(
                    id, title, description, start_time, end_time, priority,
                    category, completed, overdue, created_at, updated_at,
                    sort_index, owner_user_id, recurrence_rule, reminder_offset, recurrence_end
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON DUPLICATE KEY UPDATE
                    title=VALUES(title),
                    description=VALUES(description),
                    start_time=VALUES(start_time),
                    end_time=VALUES(end_time),
                    priority=VALUES(priority),
                    category=VALUES(category),
                    completed=VALUES(completed),
                    overdue=VALUES(overdue),
                    updated_at=VALUES(updated_at),
                    sort_index=VALUES(sort_index),
                    owner_user_id=VALUES(owner_user_id),
                    recurrence_rule=VALUES(recurrence_rule),
                    reminder_offset=VALUES(reminder_offset),
                    recurrence_end=VALUES(recurrence_end)
                """;
            case FIREBIRD -> """
                UPDATE OR INSERT INTO tasks(
                    id, title, description, start_time, end_time, priority,
                    category, completed, overdue, created_at, updated_at,
                    sort_index, owner_user_id, recurrence_rule, reminder_offset, recurrence_end
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                MATCHING(id)
                """;
        };
    }

    public String upsertSettingSql() {
        return switch (this) {
            case SQLITE, POSTGRESQL -> """
                INSERT INTO app_settings(key, value, updated_at) VALUES(?, ?, CURRENT_TIMESTAMP)
                ON CONFLICT(key) DO UPDATE SET
                    value=excluded.value,
                    updated_at=CURRENT_TIMESTAMP
                """;
            case MYSQL -> """
                INSERT INTO app_settings(`key`, value, updated_at) VALUES(?, ?, CURRENT_TIMESTAMP)
                ON DUPLICATE KEY UPDATE
                    value=VALUES(value),
                    updated_at=CURRENT_TIMESTAMP
                """;
            case FIREBIRD -> """
                UPDATE OR INSERT INTO app_settings(key, value, updated_at) VALUES(?, ?, CURRENT_TIMESTAMP)
                MATCHING(key)
                """;
        };
    }

    public String addColumnSql(String table, String columnDefinition) {
        if (supportsIfNotExistsOnAddColumn()) {
            return "ALTER TABLE " + table + " ADD COLUMN IF NOT EXISTS " + columnDefinition;
        }
        return "ALTER TABLE " + table + " ADD COLUMN " + columnDefinition;
    }

    public String topRows(int count) {
        return this == FIREBIRD ? "FIRST " + count : "LIMIT " + count;
    }

    private String inferMatchingColumns(String table) {
        return switch (table) {
            case "tags" -> "name";
            case "app_settings" -> "key";
            case "task_tags" -> "task_id, tag_id";
            default -> "id";
        };
    }
}
