-- Firebird / Red DB schema for ToDoList

CREATE TABLE users (
    id VARCHAR(64) PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    password_salt VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    reset_code VARCHAR(32),
    reset_code_expires_at TIMESTAMP
);

CREATE TABLE tasks (
    id VARCHAR(64) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description BLOB SUB_TYPE TEXT,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    priority VARCHAR(32) NOT NULL,
    category VARCHAR(32) NOT NULL,
    completed SMALLINT NOT NULL DEFAULT 0,
    overdue SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    sort_index INTEGER NOT NULL DEFAULT 0,
    owner_user_id VARCHAR(64),
    recurrence_rule VARCHAR(64),
    reminder_offset INTEGER NOT NULL DEFAULT 0,
    recurrence_end TIMESTAMP,
    CONSTRAINT fk_tasks_owner FOREIGN KEY (owner_user_id) REFERENCES users(id)
);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    color VARCHAR(16) NOT NULL DEFAULT '#95a5a6'
);

CREATE TABLE task_tags (
    task_id VARCHAR(64) NOT NULL,
    tag_id BIGINT NOT NULL,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_task_tags PRIMARY KEY (task_id, tag_id),
    CONSTRAINT fk_task_tags_task FOREIGN KEY (task_id) REFERENCES tasks(id),
    CONSTRAINT fk_task_tags_tag FOREIGN KEY (tag_id) REFERENCES tags(id)
);

CREATE TABLE task_statistics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    operation_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    details BLOB SUB_TYPE TEXT,
    CONSTRAINT fk_task_statistics_task FOREIGN KEY (task_id) REFERENCES tasks(id)
);

CREATE TABLE app_settings (
    key VARCHAR(128) PRIMARY KEY,
    value BLOB SUB_TYPE TEXT,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_tasks_completed ON tasks(completed);
CREATE INDEX idx_tasks_priority ON tasks(priority);
CREATE INDEX idx_tasks_category ON tasks(category);
CREATE INDEX idx_tasks_end_time ON tasks(end_time);
CREATE INDEX idx_tasks_owner_user_id ON tasks(owner_user_id);
CREATE INDEX idx_task_tags_task_id ON task_tags(task_id);
CREATE INDEX idx_task_statistics_task_id ON task_statistics(task_id);
